sudo: required
services:
  - docker
language: java
dist: bionic
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_IMAGE=zp8358/fileuploadservice:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
before_install:
  - chmod +x mvnw
  - docker network create rso
  - docker run -d --network rso --name postgres-filedata -e POSTGRES_USER=dbuser -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=fileData -p 5432:5432 postgres:13
script:
  - mvn clean package -U -Dmaven.test.skip=True
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"