sudo: required
services:
  - docker
language: java
dist: bionic
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
env:
  global:
    - DOCKER_IMAGE=zp8358/imageuploadservice:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"