app:
  datasource:
    # docker run -d --name postgres-imagedata -e POSTGRES_USER=dbuser -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=imageData -p 5432:5432 postgres:13
    jdbc-url: jdbc:postgresql://localhost:5432/imageData
    username: dbuser
    password: postgres
    pool-size: 30
