apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-upload-service
  template:
    metadata:
      labels:
        app: file-upload-service
    spec:
      containers:
        - image: zp8358/fileuploadservice:1.0.0-SNAPSHOT-37.1
          #resources:
            #requests:
              #cpu: "50m"
            #limits:
              #cpu: "70m"
          name: file-upload-service
          env:
            - name: DBURL
              value: jdbc:postgresql://kandula.db.elephantsql.com:5432/obaguetb
            - name: DBUSERNAME
              value: obaguetb
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pass-file-upload
                  key: DBPASSWORD
            - name: AWSAPIKEY
              valueFrom:
                secretKeyRef:
                  name: aws-public
                  key: AWSAPIKEY
            - name: AWSAPISECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWSAPISECRET
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/files/checks/health/liveness
              port: server
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /v1/files/checks/health/readiness
              port: server
            initialDelaySeconds: 120
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: file-upload-service
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: file-upload-service