apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-upload-service
  template:
    metadata:
      labels:
        app: file-upload-service
    spec:
      containers:
        - image: zp8358/fileuploadservice:1.0.0-SNAPSHOT-28.1
          name: file-upload-service
          env:
            - name: DBURL
              value: jdbc:postgresql://kandula.db.elephantsql.com:5432/obaguetb
            - name: DBUSERNAME
              value: obaguetb
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpasssecret
                  key: DBPASSWORD
            - name: AWSAPIKEY
              valueFrom:
                secretKeyRef:
                  name: publicapisecret
                  key: AWSAPIKEY
            - name: AWSAPISECRET
              valueFrom:
                secretKeyRef:
                  name: secretapisecret
                  key: AWSAPISECRET
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: file-upload-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: file-upload-service